### ISSUE TITLE
Training files

### ISSUE THREAD

**Issue by jblyberg** [julianpoy/ingredient-instruction-classifier#7]
First off, thanks for sharing this project. I'm trying to wrap my head around tensorflow and this is a small enough app that it's given me some handles to get started with. 

Looking through the code, I noticed that you full in training files from a data directory that's not included (`data/ingredients.json`,  etc). I'm very curious to see what those look like, how much data is in them, etc. If you're willing to share those, I'd very much appreciate it. If not that's fine too.

Thanks again.

**Comment by julianpoy** [comment]
👋🏼 Hey there!

Totally missed this issue. I know it's been two months, super sorry for that!

Unfortunately the training data for this is not something I can publish at the moment since it's built from a mix of data some of which isn't public.
